// src/content/config.ts — taruishi-burger-astro
// Generated by app-bootstrap (astro-static template, #5321)
// content collections の型定義。必要に応じてコレクションを追加してください。
import { defineCollection, z } from 'astro:content';

// 例: ブログ記事コレクション
// const blog = defineCollection({
//   type: 'content',
//   schema: z.object({
//     title: z.string(),
//     description: z.string(),
//     pubDate: z.coerce.date(),
//     updatedDate: z.coerce.date().optional(),
//   }),
// });

// export const collections = { blog };

// デフォルトは空のコレクション定義（#5353 テーマシステムで拡張予定）
export const collections = {};
