// astro.config.mjs — taruishi-burger-astro
// Generated by app-bootstrap (astro-static template, #5321)
import { defineConfig } from 'astro/config';

export default defineConfig({
  output: 'static',
  // Docker (eai-systemctl): ASTRO_BASE 未設定 → base: '/' (ルート)
  // GitHub Pages (sites/<name>/): deploy workflow で ASTRO_BASE=/sites/<name> を設定
  base: process.env.ASTRO_BASE || '/',
});
