// astro.config.mjs — gurinbizu-game
// Generated by app-bootstrap (astro-static template, #5321)
import { defineConfig } from 'astro/config';

export default defineConfig({
  output: 'static',
  // base: サブパス配信対応 (#5411)。app-bootstrap が SITE_PATH から ASTRO_BASE を算出し
  //   deploy.yml の Build ステップで env として注入する（sites/<name> → /sites/<name>）。
  //   ルート配信（SITE_PATH=.）では ASTRO_BASE が空文字になり '/' にフォールバックする（後方互換）。
  //   注意: 画像・静的アセットは絶対パス（/images/...）でなく
  //   `import.meta.env.BASE_URL` を前置すること（README 参照）。
  base: process.env.ASTRO_BASE || '/',
  // content collections は src/content/ 配下に自動認識される
  // テーマ (#5318)・多言語 (#5319)・マルチページ (#5320) はこの config を拡張して実装
});
